import Head from "next/head";
import {useEffect, useState} from "react";
import {Box, Stack} from "@mui/material";
import {useDispatch} from "react-redux";
import {enableMapSet} from "immer";
import {useAddress, useWeb3Context} from "../web3/web3-context";
import MenuBar from "../components/header/AppBar";
import Footer from "../components/footer/Footer";
import {loadApp} from "../store/app-slice";
import {Web3Params} from "../store/utils/params";
import Link from "next/link";

interface LayoutProps {
    children: React.ReactNode
}

const Layout = ({children}: LayoutProps) => {
    const dispatch = useDispatch();
    const address = useAddress();
    const {connect, provider, hasCachedProvider, chainID, connected, web3Modal} = useWeb3Context();
    const [walletChecked, setWalletChecked] = useState(false);


    useEffect(() => {

        if (web3Modal === undefined) return

        if (hasCachedProvider()) {
            connect().then(() => {
                setWalletChecked(true);
            });
        } else {
            setWalletChecked(true);
        }
    }, [web3Modal]);

    useEffect(() => {
        enableMapSet()

        let p: Web3Params = {
            networkID: chainID, provider: provider, address: address
        }
        if (connected) {
            dispatch(loadApp(p))
        }

    }, [connected])

    return (
        <Box height="100vh" display="flex" flexDirection="column">
            <Head>
                <title>Odyssey Mint Central</title>
                <meta name="" content="Vader NFT"/>
                <link rel="icon" href="/favicon.ico"/>

                <link rel="stylesheet" href="/fonts/KeepCalm.css"/>

                <meta name="twitter:card" content="summary"/>
                <meta name="twitter:site" content="@invaders_army"/>
                <meta name="twitter:title" content="Invader"/>
                <meta name="twitter:description"
                      content="InVaders are 55,555 galactic army of Viking warriors! Unique half human and half cyborg warriors, generated by Artificial Intelligence in the year 2055."/>
                <meta name="twitter:image"
                      content="https://i.ibb.co/wYmT1fB/vk.png"/>
            </Head>

            <MenuBar/>


            <main>
                {children}
            </main>


            <footer>
                <Footer/>
            </footer>
        </Box>
    )

}

export default Layout
